# frozen_string_literal: true

module Engine
  module Game
    module G18IL
      module Corporations
        CORPORATIONS =
          [
              {
                float_percent: 100,
                sym: 'P&BV',
                name: 'Peoria and Bureau Valley Railroad',
                logo: '18_il/P&BV.alt',
                simple_logo: '18_il/P&BV.alt',
                shares: [100],
                tokens: [0],
                coordinates: 'E8',
                color: '#2165ae',
                type: 'two_share',
                max_ownership_percent: 100,
                always_market_price: true,
              },
              {
                float_percent: 100,
                sym: 'NC',
                name: 'Northern Cross Railroad',
                logo: '18_il/NC.alt',
                simple_logo: '18_il/NC.alt',
                shares: [100],
                tokens: [0],
                coordinates: 'E12',
                color: '#694a98',
                type: 'two_share',
                max_ownership_percent: 100,
                always_market_price: true,
              },
              {
                float_percent: 40,
                sym: 'G&CU',
                name: 'Galena and Chicago Union Railroad',
                logo: '18_il/G&CU.alt',
                simple_logo: '18_il/G&CU.alt',
                shares: [40, 20, 20, 20],
                tokens: [0],
                coordinates: 'E2',
                color: '#e0c6ae',
                text_color: 'black',
                type: 'five_share',
                always_market_price: true,
              },
              {
                float_percent: 40,
                sym: 'RI',
                name: 'Rock Island Line',
                logo: '18_il/RI.alt',
                simple_logo: '18_il/RI.alt',
                shares: [40, 20, 20, 20],
                tokens: [0],
                coordinates: 'C6',
                color: '#e84b1c',
                type: 'five_share',
                always_market_price: true,
                text_color: 'black',
              },
              {
                float_percent: 40,
                sym: 'CBQ',
                name: 'Chicago, Burlington, & Quincy',
                logo: '18_il/CBQ.alt',
                simple_logo: '18_il/CBQ.alt',
                shares: [40, 20, 20, 20],
                tokens: [0],
                coordinates: 'B11',
                color: '#8dc8e7',
                type: 'five_share',
                always_market_price: true,
                text_color: 'black',
              },
              {
                float_percent: 40,
                sym: 'V',
                name: 'Vandalia Railroad',
                logo: '18_il/V.alt',
                simple_logo: '18_il/V.alt',
                shares: [40, 20, 20, 20],
                tokens: [0],
                coordinates: 'G16',
                color: '#fdc600',
                type: 'five_share',
                always_market_price: true,
                text_color: 'black',
              },
              {
                float_percent: 20,
                sym: 'WAB',
                name: 'Wabash Railroad',
                logo: '18_il/WAB.alt',
                simple_logo: '18_il/WAB.alt',
                shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
                tokens: [0],
                coordinates: 'I6',
                color: '#7e8892',
                text_color: 'black',
                type: 'ten_share',
                always_market_price: true,
              },
              {
                float_percent: 20,
                sym: 'C&EI',
                name: 'Chicago and Eastern Illinois Railroad',
                logo: '18_il/C&EI.alt',
                simple_logo: '18_il/C&EI.alt',
                shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
                tokens: [0],
                coordinates: 'H21',
                color: '#7d3b2c',
                type: 'ten_share',
                always_market_price: true,
                text_color: 'white',
              },
              {
                sym: 'IC',
                name: 'Illinois Central Railroad',
                logo: '18_il/IC.alt',
                simple_logo: '18_il/IC.alt',
                shares: [20, 10, 10, 10, 10, 10, 10, 10, 10],
                tokens: [0],
                coordinates: 'H3',
                city: 2,
                color: '#0d8743',
                type: 'ten_share',
                always_market_price: true,
                floatable: false,
              },
            ].freeze
      end
    end
  end
end
